"""English negative sentiment lexicon.

Used by the XLM-R fallback path and shared with other models that need
an English negative lexicon. Words are stored in lowercase so that simple
whitespace tokenization matches reliably.
"""

NEGATIVE_WORDS_EN: set[str] = {
    # --- Core adjectives ---
    "bad", "terrible", "sad", "hate", "problem", "fail", "weak",
    "negative", "worst", "slow", "expensive", "poor",
    "awful", "horrible", "horrendous", "atrocious", "dreadful",
    "appalling", "lousy", "crappy", "shitty", "sucky", "garbage",
    "trash", "junk", "rubbish", "worthless", "useless", "pointless",
    "meaningless", "hopeless", "helpless", "worthless", "inferior",
    "subpar", "sub-standard", "mediocre", "lackluster", "uninspiring",
    "unimpressive", "disappointing", "disappointed", "disappoints",
    "disappointment", "underwhelming", "anticlimactic", "flat", "bland",
    "dull", "boring", "bored", "tedious", "monotonous", "mundane",
    "tiresome", "troublesome", "annoying", "annoyed", "irritating",
    "irritated", "frustrating", "frustrated", "aggravating", "aggravated",
    "vexing", "vexed", "galling", "infuriating", "infuriated", "maddening",

    # --- Emotions & feelings ---
    "sad", "sadness", "unhappy", "depressed", "depression", "melancholy",
    "melancholic", "sorrow", "sorrowful", "grief", "grieving", "mourning",
    "mournful", "heartbroken", "heartbreak", "devastated", "devastating",
    "shattered", "crushed", "broken", "wounded", "hurt", "hurting",
    "pain", "painful", "aching", "ache", "sore", "suffering", "suffer",
    "agony", "agonizing", "torment", "tormented", "anguish", "anguished",
    "despair", "despairing", "desperate", "desperation", "hopeless",
    "helpless", "forlorn", "forsaken", "abandoned", "lonely", "loneliness",
    "alone", "isolated", "isolated", "alienated", "alienation",
    "rejected", "rejection", "abandoned", "betrayed", "betrayal",
    "cheated", "deceived", "deception", "lied", "lies", "lying",
    "angry", "anger", "rage", "furious", "fury", "wrath", "indignant",
    "resentful", "resentment", "bitter", "bitterness", "hostile",
    "hostility", "vengeful", "vengeance", "revenge", "spiteful", "spite",
    "malicious", "malice", "cruel", "cruelty", "brutal", "brutality",
    "vicious", "savage", "merciless", "ruthless", "heartless", "cold",
    "cold-hearted", "callous", "indifferent", "apathetic", "numb",
    "fear", "fearful", "afraid", "scared", "scary", "terrified",
    "terrifying", "terror", "horror", "horrific", "horrified",
    "panic", "panicking", "panicked", "anxious", "anxiety", "nervous",
    "worried", "worry", "worrying", "dread", "dreading", "dreaded",
    "stressed", "stress", "stressed", "tense", "tension", "uneasy",
    "restless", "disturbed", "disturbing", "troubled", "trouble",
    "concerned", "concern", "dismay", "dismayed", "dismaying",

    # --- Problems & difficulties ---
    "problem", "problems", "issue", "issues", "trouble", "troubles",
    "difficulty", "difficult", "hard", "tough", "challenging", "challenge",
    "obstacle", "obstacles", "barrier", "barriers", "hurdle", "hurdles",
    "struggle", "struggling", "struggles", "fight", "fighting", "battle",
    "battling", "conflict", "conflicts", "dispute", "disputes",
    "argument", "arguments", "quarrel", "quarreling", "feud", "feuding",
    "crisis", "crises", "disaster", "disasters", "catastrophe",
    "catastrophic", "tragedy", "tragic", "tragedies", "calamity",
    "calamitous", "cataclysm", "cataclysmic", "emergency", "urgency",
    "urgent", "critical", "dire", "grave", "severe", "serious",
    "menace", "threat", "threatening", "threatened", "danger", "dangerous",
    "hazard", "hazardous", "risk", "risky", "peril", "perilous",
    "jeopardy", "complication", "complications", "complicated", "complex",
    "convoluted", "intricate", "perplexing", "baffling", "confusing",
    "confused", "puzzling", "puzzled", "mystifying", "mysterious",
    "enigmatic", "ambiguous", "vague", "unclear", "obscure", "murky",

    # --- Failure & weakness ---
    "fail", "failed", "failing", "failure", "failures", "loser",
    "losing", "lost", "loss", "losses", "defeat", "defeated",
    "beaten", "crushed", "routed", "overcome", "overwhelmed",
    "collapsed", "collapse", "collapsing", "ruined", "ruin", "ruining",
    "wrecked", "wreck", "wrecking", "destroyed", "destroy", "destroying",
    "demolished", "demolish", "shattered", "shatter", "broken", "break",
    "breaking", "damaged", "damage", "damaging", "harm", "harmful",
    "harming", "injured", "injury", "injure", "wounded", "wound",
    "weak", "weakness", "feeble", "frail", "fragile", "vulnerable",
    "defenseless", "helpless", "powerless", "impotent", "inadequate",
    "insufficient", "lacking", "deficient", "defective", "faulty",
    "flawed", "imperfect", "blemished", "tainted", "corrupt", "corrupted",
    "corrupting", "rotten", "decay", "decaying", "decomposed", "spoiled",
    "spoiling", "tainted", "contaminated", "polluted", "poisoned",
    "toxic", "poison", "poisonous", "venomous", "noxious", "harmful",

    # --- Negative qualities ---
    "stupid", "dumb", "idiot", "idiotic", "foolish", "silly", "ignorant",
    "ignorance", "clueless", "brainless", "mindless", "thoughtless",
    "careless", "reckless", "irresponsible", "irresponsibility",
    "negligent", "negligence", "lazy", "laziness", "indolent", "slothful",
    "slack", "sloppy", "sloppiness", "messy", "disorderly", "chaotic",
    "chaos", "confusion", "confused", "disorganized", "haphazard",
    "random", "arbitrary", "capricious", "erratic", "inconsistent",
    "unreliable", "undependable", "untrustworthy", "shady", "sketchy",
    "dubious", "doubtful", "suspicious", "suspect", "questionable",
    "shameful", "shame", "shameless", "disgraceful", "disgrace",
    "scandal", "scandalous", "outrageous", "outrage", "infamous",
    "notorious", "disreputable", "dishonest", "dishonesty", "deceitful",
    "deceit", "lying", "lies", "liar", "cheat", "cheating", "fraud",
    "fraudulent", "scam", "scammer", "con", "swindle", "swindler",
    "fake", "phony", "fraud", "counterfeit", "forgery", "forged",
    "hypocrite", "hypocrisy", "hypocritical", "two-faced", "treacherous",
    "treachery", "perfidious", "perfidy", "disloyal", "disloyalty",
    "traitor", "traitorous", "betrayer", "betrayal", "backstabbing",

    # --- Negative behavior ---
    "hate", "hated", "hatred", "hateful", "detest", "detestable",
    "loathe", "loathsome", "despise", "despicable", "abhor", "abhorrent",
    "repugnant", "repulsive", "repulsed", "revolting", "disgusting",
    "disgust", "disgusted", "nauseating", "nauseous", "sickening",
    "sick", "gross", "yuck", "ew", "ugh", "bleh", "nasty", "vile",
    "foul", "rank", "rancid", "putrid", "fetid", "smelly", "stinky",
    "stank", "stunk", "reek", "reeking", "malodorous", "unpleasant",
    "offensive", "offended", "insulting", "insult", "insulted",
    "abusive", "abuse", "abused", "mistreat", "mistreated", "mistreatment",
    "bully", "bullying", "bullied", "harass", "harassment", "harassed",
    "intimidate", "intimidating", "intimidated", "threaten", "threatened",
    "coerce", "coercion", "blackmail", "extort", "extortion", "extorted",
    "manipulate", "manipulating", "manipulated", "manipulation",
    "exploit", "exploiting", "exploited", "exploitation", "oppress",
    "oppression", "oppressed", "persecute", "persecution", "persecuted",
    "discriminate", "discrimination", "discriminated", "bigotry",
    "prejudice", "prejudiced", "racist", "racism", "sexist", "sexism",
    "xenophobia", "xenophobic", "homophobia", "homophobic", "islamophobia",

    # --- Pain & discomfort ---
    "pain", "painful", "ache", "aching", "sore", "soreness", "hurt",
    "hurting", "hurts", "suffer", "suffering", "agony", "agonizing",
    "torment", "tormenting", "tormented", "torture", "tortured",
    "torturing", "anguish", "anguished", "wound", "wounded", "injury",
    "injured", "hurt", "damage", "damaged", "sick", "ill", "illness",
    "disease", "sickness", "sick", "unwell", "ailing", "poorly",
    "fever", "feverish", "nausea", "nauseous", "vomit", "vomiting",
    "dizzy", "dizziness", "faint", "fainting", "exhausted", "exhaustion",
    "fatigue", "fatigued", "tired", "tiring", "weary", "weariness",
    "drained", "depleted", "burnt-out", "burnout", "overworked",
    "overwhelmed", "overwhelm", "stressed", "stress", "strained",
    "tense", "tension", "sore", "stiff", "stiffness", "cramp",
    "cramping", "spasm", "spasms", "throbbing", "throbbing", "stabbing",
    "piercing", "sharp", "shooting", "burning", "stinging", "raw",

    # --- Negative descriptions ---
    "slow", "sluggish", "sluggish", "laggy", "lagging", "lag", "delay",
    "delayed", "delays", "tardy", "late", "overdue", "behind",
    "backlogged", "bottleneck", "bottlenecks", "stalled", "stalling",
    "stuck", "halted", "halt", "frozen", "freeze", "freezing",
    "crash", "crashed", "crashing", "broken", "broke", "bug", "bugs",
    "buggy", "glitch", "glitches", "glitchy", "error", "errors",
    "fault", "faults", "faulty", "defect", "defects", "defective",
    "flaw", "flaws", "flawed", "malfunction", "malfunctions",
    "malfunctioning", "outage", "outages", "downtime", "unavailable",
    "unreachable", "offline", "down", "dead", "unresponsive",
    "unresponsive", "hung", "hang", "hanging", "stuck", "jammed",
    "jammed", "blocked", "blocking", "obstructed", "obstructing",
    "impeded", "impeding", "hinder", "hindering", "hindered",
    "hamper", "hampered", "hampering", "thwart", "thwarted",
    "frustrate", "frustrated", "frustrating", "frustration",

    # --- Common negative expressions ---
    "no", "not", "never", "none", "nothing", "nobody", "nowhere",
    "neither", "nor", "cannot", "can't", "cant", "won't", "wont",
    "don't", "dont", "doesn't", "doesnt", "didn't", "didnt", "isn't",
    "isnt", "aren't", "arent", "wasn't", "wasnt", "weren't", "werent",
    "haven't", "havent", "hasn't", "hasnt", "hadn't", "hadnt",
    "wouldn't", "wouldnt", "shouldn't", "shouldnt", "couldn't",
    "couldnt", "mightn't", "mightnt", "mustn't", "mustnt",
    "stop", "quit", "give-up", "giveup", "abandon", "abandoned",
    "surrender", "defeat", "concede", "yield", "retreat", "withdraw",
    "resign", "resigned", "step-down", "stepdown", "fired", "sacked",
    "laid-off", "laidoff", "unemployed", "jobless", "broke", "bankrupt",
    "bankruptcy", "debt", "debts", "indebted", "owe", "owing", "owed",
    "poor", "poverty", "impoverished", "destitute", "needy", "deprived",
    "starving", "starve", "starvation", "hungry", "hunger", "thirst",
    "thirsty", "homeless", "evicted", "eviction", "foreclosure",
    "foreclosed", "repossession", "repossessed", "default", "defaulted",

    # --- Dialectal / colloquial negative forms ---
    "sucks", "sucked", "suck", "blows", "blew", "blow", "bites",
    "biting", "stinks", "stink", "stank", "stunk", "reeks", "reek",
    "lame", "whack", "wack", "weak", "soft", "bogus", "janky",
    "jank", "sketchy", "sketch", "shady", "sus", "suspect", "sketch",
    "trash", "trashed", "garbage", "dumpster", "dumpster-fire",
    "dumpsterfire", "dumpster", "dump", "landfill", "waste", "wasted",
    "wasteful", "wasting", "squander", "squandered", "squandering",
    "flush", "flushed", "toss", "tossed", "dumped", "ditch", "ditched",
    "scrap", "scrapped", "junk", "junked", "scrap", "scrapheap",
    "reject", "rejected", "rejection", "rejects", "deny", "denied",
    "denying", "refuse", "refused", "refusing", "decline", "declined",
    "veto", "vetoed", "nix", "nixed", "quash", "quashed", "revoke",
    "revoked", "repeal", "repealed", "rescind", "rescinded", "annul",
    "annulled", "invalidate", "invalidated", "nullify", "nullified",
    "void", "voided", "cancel", "canceled", "cancelled", "abort",
    "aborted", "aborting", "terminate", "terminated", "terminating",
    "end", "ended", "ending", "cease", "ceased", "discontinue",
    "discontinued", "halt", "halted", "pause", "paused", "suspend",
    "suspended", "freeze", "frozen", "stall", "stalled", "stuck",
}
