from app.config import get_settings
from app.models.base_model import BaseSentimentModel, SentimentPrediction
from app.models.lexicons import NEGATIVE_WORDS_AR, POSITIVE_WORDS_AR

settings = get_settings()


class AraBERTSentimentModel(BaseSentimentModel):
    name = "arabert"

    positive_words = POSITIVE_WORDS_AR
    negative_words = NEGATIVE_WORDS_AR

    def __init__(self):
        self.pipeline = None
        if settings.enable_hf_models:
            self._try_load_pipeline()

    def _try_load_pipeline(self):
        try:
            from transformers import pipeline
            self.pipeline = pipeline("text-classification", model=settings.arabert_model_name, top_k=None)
        except Exception:
            self.pipeline = None

    def predict(self, text: str, language: str = "ar", context: list[str] | None = None) -> SentimentPrediction:
        if self.pipeline:
            return self._predict_hf(text)

        tokens = set(text.lower().split())
        pos = len(tokens & self.positive_words)
        neg = len(tokens & self.negative_words)

        if pos > neg:
            probs = {"positive": 0.75, "negative": 0.10, "neutral": 0.15}
        elif neg > pos:
            probs = {"positive": 0.10, "negative": 0.75, "neutral": 0.15}
        else:
            probs = {"positive": 0.25, "negative": 0.20, "neutral": 0.55}

        label = max(probs, key=probs.get)
        return SentimentPrediction(
            model_name=self.name,
            label=label,
            score=probs[label],
            probabilities=probs,
            explanation="AraBERT fallback lexicon was used. Enable HF models for real fine-tuned inference.",
        )

    def _predict_hf(self, text: str) -> SentimentPrediction:
        raw = self.pipeline(text)[0]
        probs = {}
        for item in raw:
            label = item["label"].lower()
            if "pos" in label or "positive" in label:
                label = "positive"
            elif "neg" in label or "negative" in label:
                label = "negative"
            else:
                label = "neutral"
            probs[label] = max(probs.get(label, 0.0), float(item["score"]))

        for label in ["positive", "negative", "neutral"]:
            probs.setdefault(label, 0.0)

        best = max(probs, key=probs.get)
        return SentimentPrediction(
            model_name=self.name,
            label=best,
            score=probs[best],
            probabilities=probs,
            explanation="Prediction generated by Hugging Face AraBERT pipeline.",
        )
